server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment_routh #ID 唯一地址就可以，最好使用服务名称
        uri: http://localhost:8001   #
        predicates:
          - Path=/**   #,

      - id: payment_routh2
        uri: http://localhost:8001
        predicates:
          - Path=/payment/get/discovery   #,


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka


